[timeline]
posts_limit = 4000
hours_limit = 24
exclude_trending = true
exclude_previously_digested_posts = true
max_user_post_count = 3

[post]
min_word_count = 8
max_age_hours = 240
languages = [ "en", "hi" ]

[scoring]
tag_boost = 1.2
account_boost = 1.2
reply_unboost = 1.5
bot_unboost = 1.2
halflife_hours = 6
tag_count_threshold = 4

[digest]
explore_frac = 0.2
threshold = 50
boosted_tags = [
  "astronomy",
  "astrophotography",
  "bangalore",
  "bengaluru",
  "compilers",
  "FunctionalProgramming",
  "Haskell",
  "India",
  "lisp",
  "NixOS",
  "PLT",
  "PLDev",
  "ProgrammingLanguages",
  "QuantifiedSelf",
  "running",
]
unboosted_tags = [
  "cats",
  "catsofmastodon",
  "nyt",
  "NewYorkTimes",
  "religion",
  "christianity",
  "mutualAid",
  "fediblock",
  "GetFediHired"
]
boosted_list_ids = [6, 7, 12]
