[timeline]
posts_limit = 4000
hours_limit = 24
exclude_trending = true
exclude_previously_digested_posts = true
max_user_post_count = 3

[post]
min_word_count = 10
max_age_hours = 120
languages = [ "en", "hi" ]

[scoring]
tag_boost = 1.2
account_boost = 1.2
halflife_hours = 6

[digest]
explore_frac = 0.2
threshold = 80
boosted_tags = [
  "astronomy",
  "astrophotography",
  "bangalore",
  "bengaluru",
  "compilers",
  "FunctionalProgramming",
  "google",
  "Haskell",
  "India",
  "lisp",
  "NixOS",
  "PLT",
  "ProgrammingLanguages",
  "QuantifiedSelf",
  "running",
  "SelfHosting",
]
boosted_list_ids = [1, 6, 12]
