name: My Mastodon Digest
on:
  push:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  update:
    name: digest
    runs-on: ubuntu-latest
    steps:
      - name: Install curl and unzip
        run: sudo apt-get install -y curl unzip
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: main
      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
      - name: python things
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download previous digest
        run: |
          curl -o ./render/previous.html https://abhin4v.github.io/mastodon_digest/
          curl -o ./render/previous2.html https://abhin4v.github.io/mastodon_digest/previous.html
      - name: Download digested_posts.json
        run: |
          curl -L -o digested_posts.json.zip https://nightly.link/abhin4v/mastodon_digest/workflows/update/main/digested_posts.json.zip
          unzip digested_posts.json.zip
      - name: run digest
        env:
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
          MASTODON_BASE_URL: ${{ secrets.MASTODON_BASE_URL }}
        run: python run.py ./render/
      - name: publish
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: render
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive digested_posts.json
        uses: actions/upload-artifact@v4
        with:
          name: digested_posts.json
          path: digested_posts.json
          retention-days: 2
          overwrite: true
