name: My Mastodon Digest
on:
  push:
  schedule:
    - cron: '0 4,9,14 * * *'
  workflow_dispatch:
jobs:
  update:
    name: digest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: main
      - name: python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: python things
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run digest
        env:
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
          MASTODON_BASE_URL: ${{ secrets.MASTODON_BASE_URL }}
          MASTODON_USERNAME: ${{ secrets.MASTODON_USERNAME }}
        run: |
          python run.py -n 24 -d 6 -e 0.2 -s ExtendedSimpleWeighted -t lax -g Haskell -g compilers -g ProgrammingLanguages -g NixOS -g PLT -g lisp -g FunctionalProgramming -g QuatifiedSelf -g SelfHosting -g running -l en -l hi
      - name: publish
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: render
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
